/**
 * Layer8 member roster for /about and /legacy.
 *
 * Updated from the AboutLateL8 member sheet — all current members plus the
 * four alumni kept for /legacy. Roles/domains are as given on the sheet.
 * `core: true` marks the club head / vice-head and each domain's head /
 * vice-head — the people shown as large cards on /about.
 */

export type MemberGroup = "Club" | "Tech" | "Events" | "Media" | "Design";

export type Member = {
  slug: string;
  name: string;
  alias?: string;
  role: string;
  group: MemberGroup;
  year?: string;
  bio: string;
  status: "current" | "alumni";
  core?: boolean;
  github?: string;
  linkedin?: string;
  portfolio?: string;
  email: string;
};

export const MEMBERS: Member[] = [
  {
    slug: "sriya-chandu",
    name: "Sriya Yashita Chandu",
    alias: "ysczie",
    role: "Club Head",
    group: "Club",
    year: "2028, CSE",
    bio: "A kunafa a day I tell you.",
    status: "current",
    core: true,
    email: "sriyachandu691@gmail.com",
  },
  {
    slug: "archita-agrawal",
    name: "Archita Agrawal",
    alias: "Archi",
    role: "Vice Club Head 26-27",
    group: "Club",
    year: "2029, CSE",
    bio: "Rage-baiting CTF players since 2025 ",
    status: "current",
    core: true,
    github: "architaagr",
    email: "architaagrawal2007@gmail.com",
  },
  {
    slug: "shubhika-pradeep",
    name: "Shubhika Pradeep",
    alias: "Bee",
    role: "Tech Head 26-27",
    group: "Tech",
    year: "2028, CSE (AI/ML)",
    bio: "You know who I am",
    status: "current",
    core: true,
    portfolio: "https://sosportfolio.vercel.app",
    email: "shubhikaiyer@gmail.com",
  },
  {
    slug: "blason-raj",
    name: "Blason Raj",
    alias: "Blason",
    role: "Head of Events 2026-27",
    group: "Events",
    year: "2028, CSE",
    bio: "We are free",
    status: "current",
    core: true,
    github: "blason2108",
    linkedin: "blason-raj",
    email: "blasonrimmanuel311@gmail.com",
  },
  {
    slug: "sohan-mr",
    name: "Sohan MR",
    role: "Media & Marketing Head",
    group: "Media",
    year: "2028, CSE",
    bio: "Think like a hacker to stop one",
    status: "current",
    core: true,
    email: "sohan.rajannavar3646@gmail.com",
  },
  {
    slug: "riddhima-agarwal",
    name: "Riddhima Agarwal",
    alias: "Riddhi",
    role: "Design Vice Head 26-27",
    group: "Design",
    year: "2029, CSE",
    bio: "I m going to bed.",
    status: "current",
    core: true,
    linkedin: "rriddhima-agarwal2004",
    email: "rriddhima.agarwal2004@gmail.com",
  },
  {
    slug: "arnav-deva",
    name: "Arnav Deva",
    alias: "Deva / Cola",
    role: "Webmaster 26-27",
    group: "Tech",
    year: "2029, CSE (AI/ML)",
    bio: "Lore in progress",
    status: "current",
    core: true,
    portfolio: "https://deva-arnav.vercel.app",
    email: "arnavdeva007@gmail.com",
  },
  {
    slug: "saakshi-mohanty",
    name: "Saakshi Mohanty",
    alias: "Saki",
    role: "Vice Head of E&O",
    group: "Events",
    year: "2029, CSE (AI/ML)",
    bio: "What the horse considers play, the monkey considers business.",
    status: "current",
    core: true,
    linkedin: "saakshi-mohanty-417285252",
    email: "saakshi.mohanty@gmail.com",
  },
  {
    slug: "amogh-garg",
    name: "Amogh Garg",
    alias: "Tomato Tomahto",
    role: "Tech Vice Head 26-27",
    group: "Tech",
    year: "2029, CSE",
    bio: "Here by talent. Mostly luck. Let's not investigate further.",
    status: "current",
    core: true,
    github: "AmoghGarg007",
    linkedin: "amogh-garg-2k7",
    email: "amoghgarg2007@gmail.com",
  },
  {
    slug: "krithika-swaminathan",
    name: "Krithika Swaminathan",
    alias: "Valkyrie",
    role: "Media and Marketing Vice Head 25-26",
    group: "Media",
    year: "2029, CSE",
    bio: "Somewhere between a plan and a plot twist",
    status: "current",
    core: true,
    linkedin: "krithikaswaminathan247",
    email: "krithikaswaminathan247@gmail.com",
  },
  {
    slug: "shreya-ajith",
    name: "Shreya Ajith",
    alias: "Ajith",
    role: "Design Head 26-27",
    group: "Design",
    year: "2028, CSE",
    bio: "pink <3",
    status: "current",
    core: true,
    email: "",
  },
  {
    slug: "avrit-sharma",
    name: "Avrit Sharma",
    alias: "dukeavi",
    role: "",
    group: "Tech",
    year: "CSE-2028",
    bio: "++++++++++[>+>+++>+++++++>++++++++++<<<<-]>>>>+++.++++++++..-----------.--.+++++++++++++++++++++++.--------------------.",
    status: "current",
    linkedin: "avrit",
    email: "",
  },
  {
    slug: "jyeshta-j",
    name: "Jyeshta J",
    alias: "jyeshta",
    role: "",
    group: "Events",
    year: "2028, CSE",
    bio: "See you Space Cowboy",
    status: "current",
    linkedin: "jyeshta-j-839500309",
    email: "jyeshtaj2006@gmail.com",
  },
  {
    slug: "ann-gracia-s",
    name: "Ann Gracia S",
    alias: "ann",
    role: "",
    group: "Events",
    year: "2025 CSE",
    bio: "That's all it is, Miles. A leap of faith",
    status: "current",
    linkedin: "ann-gracia-s-567a54356",
    email: "ann.gracia07@gmail.com",
  },
  {
    slug: "srivaibhav-n",
    name: "Srivaibhav N",
    alias: "Redslayer112",
    role: "",
    group: "Tech",
    year: "2028, CSE",
    bio: "",
    status: "current",
    email: "vaibhav.tolearn@gmail.com",
  },
  {
    slug: "achyuth-jois-m",
    name: "Achyuth Jois M",
    alias: "Shankar Nag",
    role: "",
    group: "Tech",
    year: "2029, CSE",
    bio: "Seek God In Humans ;)",
    status: "current",
    github: "jois-code",
    linkedin: "achyuthjoism",
    portfolio: "https://jois-code.vercel.app",
    email: "achyuthjoism@gmail.com",
  },
  {
    slug: "chatresh-ramasai-gudi",
    name: "Chatresh Ramasai Gudi",
    alias: "Chatresh",
    role: "",
    group: "Tech",
    year: "3 & CSE",
    bio: "Trust. Verify. Repeat.",
    status: "current",
    linkedin: "chatreshgudi",
    email: "chatreshrsg0202@gmail.com",
  },
  {
    slug: "aks-raj-singh",
    name: "Aks Raj Singh",
    role: "",
    group: "Media",
    year: "24-28 CSE",
    bio: "FERGIE TIME",
    status: "current",
    email: "aksvardhan2000@gmail.com",
  },
  {
    slug: "krishnaja-jinka",
    name: "Krishnaja Jinka",
    alias: "acrylicgecko",
    role: "",
    group: "Events",
    year: "2029 CSE",
    bio: "Always down for a new project, a spontaneous idea, or a mocha.",
    status: "current",
    email: "krish30.j@gmail.com",
  },
  {
    slug: "rithvik-deepak",
    name: "Rithvik Deepak",
    alias: "DPES",
    role: "",
    group: "Media",
    year: "2027, CSE (AI/ML)",
    bio: "Turning curiosity into impact, one challenge at a time.",
    status: "current",
    github: "rithvikd0605",
    linkedin: "rithvik-deepak-0992b136a",
    email: "rithvik0605@gmail.com",
  },
  {
    slug: "hiranmayi-b",
    name: "Hiranmayi B",
    alias: "Hiran",
    role: "",
    group: "Events",
    year: "2029, AIML",
    bio: "",
    status: "current",
    linkedin: "hiranmayi-b-1426493bb",
    email: "baskarhiran@gmail.com",
  },
  {
    slug: "nandana-shyam",
    name: "Nandana Shyam",
    alias: "nandu",
    role: "",
    group: "Media",
    year: "2029, AIML",
    bio: "kya tum mantally challenged ho my bwoy",
    status: "current",
    linkedin: "nandana-shyam-644248380",
    email: "nandanashyam@gmail.com",
  },
  {
    slug: "ianna-elizabeth-reni",
    name: "Ianna Elizabeth Reni",
    alias: "Eliza",
    role: "",
    group: "Tech",
    year: "2028, CSE",
    bio: "Living in fiction",
    status: "current",
    email: "ianna.elizabeth.reni@gmail.com",
  },
  {
    slug: "himani-nune",
    name: "Himani Nune",
    role: "",
    group: "Events",
    year: "2028, CSE",
    bio: "Gimme food-",
    status: "current",
    linkedin: "himani-nune-41a03723b",
    email: "nune.himani@gmail.com",
  },
  {
    slug: "krisha-varma-k",
    name: "Krisha Varma K",
    role: "",
    group: "Events",
    year: "2029, CSE",
    bio: "Debugging my life since forever.",
    status: "current",
    linkedin: "krisha-varma-konduru-4103aa426",
    email: "krishavarma27@gmail.com",
  },
  {
    slug: "prajwal-m",
    name: "Prajwal M",
    alias: "PixelAlgorithm",
    role: "",
    group: "Tech",
    year: "2028 CSE",
    bio: "Be the exploit !",
    status: "current",
    linkedin: "prajwal-m-",
    email: "studies.prajwalm@gmail.com",
  },
  {
    slug: "ankit-bembalgi",
    name: "Ankit Bembalgi",
    alias: "Ankit",
    role: "",
    group: "Tech",
    year: "2024-28 AIML",
    bio: "Put some shit da idc",
    status: "current",
    portfolio: "https://ankitbembalgi.vercel.app",
    email: "ankitbembalgi@gmail.com",
  },
  {
    slug: "p-mahema-sai",
    name: "P Mahema Sai",
    alias: "Mah",
    role: "",
    group: "Events",
    year: "2028, CSE(AIML)",
    bio: "If the plots good, Im staying.",
    status: "current",
    linkedin: "mahema-sai",
    email: "mahemasai14@gmail.com",
  },
  {
    slug: "sai-sudeshna",
    name: "Sai Sudeshna",
    alias: "Sudeshna",
    role: "",
    group: "Media",
    year: "2028, CSE",
    bio: "With great password comes great security",
    status: "current",
    email: "saisudeshna@gmail.com",
  },
  {
    slug: "isha-desai",
    name: "Isha Desai",
    role: "",
    group: "Media",
    year: "2029, CSE",
    bio: "Designing behind the firewall.",
    status: "current",
    email: "ishasd2308@gmail.com",
  },
  {
    slug: "sowmya-ramesh",
    name: "Sowmya Ramesh",
    alias: "Sowmya",
    role: "",
    group: "Design",
    year: "2028, CSE",
    bio: "If you cant convince them, confuse them",
    status: "current",
    linkedin: "sowmya-ramesh-843662374",
    email: "",
  },
  {
    slug: "anish",
    name: "Anish",
    role: "",
    group: "Tech",
    year: "2 CSE",
    bio: "Every system has a weakness. Find it",
    status: "current",
    email: "",
  },
  {
    slug: "varunavi-kumbar",
    name: "Varunavi Kumbar",
    role: "",
    group: "Design",
    year: "2029, CSE",
    bio: "Designing ideas into impact",
    status: "current",
    linkedin: "varunavi-kumbar-9104242a8",
    email: "",
  },
  {
    slug: "shreya-surya-prakash",
    name: "Shreya Surya Prakash",
    alias: "Shreya",
    role: "",
    group: "Events",
    year: "2028, ECE",
    bio: "Keeping it together (mostly)",
    status: "current",
    linkedin: "shreya-surya-prakash-8572023a6",
    email: "",
  },
  {
    slug: "rashi-sharan",
    name: "Rashi Sharan",
    alias: "Rashi",
    role: "",
    group: "Events",
    year: "2029, CSE",
    bio: "Dancing & vibing my way through life",
    status: "current",
    linkedin: "rashi-sharan-789219363",
    email: "",
  },
  {
    slug: "sreehaas-vangara",
    name: "Sreehaas Vangara",
    alias: "sreehaas",
    role: "",
    group: "Tech",
    year: "2029, CSE-AIML",
    bio: "i forgot",
    status: "current",
    linkedin: "sreehaas-vangara-72143b392",
    email: "",
  },
  {
    slug: "shivangi-tiwari",
    name: "Shivangi Tiwari",
    role: "",
    group: "Events",
    year: "2029, AIML",
    bio: "24/7 concert, 100 tabs open",
    status: "current",
    email: "",
  },
  {
    slug: "hemal-s",
    name: "Hemal S",
    role: "",
    group: "Events",
    year: "2029, CSE(AIML)",
    bio: "",
    status: "current",
    linkedin: "hemal-s-771a21386",
    email: "",
  },
  {
    slug: "nikhita-medayhal",
    name: "Nikhita Medayhal",
    alias: "bm0",
    role: "",
    group: "Tech",
    year: "2029, CSE",
    bio: "Always rely on your grey cells",
    status: "current",
    github: "NikhitaMedayhal",
    email: "",
  },
  {
    slug: "rishabh-singh",
    name: "Rishabh Singh",
    alias: "Mani",
    role: "",
    group: "Media",
    year: "2028, AIML",
    bio: "Keep grinding through the struggle until it becomes beautiful.",
    status: "current",
    github: "notrishabh-git",
    email: "rishabhsingh3842@gmail.com",
  },
  {
    slug: "manasi-trivedi",
    name: "Manasi Trivedi",
    alias: "MnM",
    role: "",
    group: "Tech",
    year: "2029, AIML",
    bio: "With great power comes a great need to take a nap — wake me up later.",
    status: "current",
    github: "Manasi-Trivedi",
    email: "btsmanasi@gmail.com",
  },
  {
    slug: "preksha-nehru",
    name: "Preksha Nehru",
    alias: "Pr1x",
    role: "",
    group: "Events",
    year: "2028, CSE",
    bio: "",
    status: "current",
    linkedin: "preksha-nehru-abbb5238b",
    email: "prekshanehru@gmail.com",
  },
  {
    slug: "manish-kumar-r",
    name: "Manish Kumar R",
    role: "",
    group: "Media",
    year: "2028, B.Pharm",
    bio: "Making moments matter.",
    status: "current",
    email: "manishmanishr26@gmail.com",
  },
  {
    slug: "arrham-jain",
    name: "Arrham Jain",
    role: "",
    group: "Tech",
    year: "2026, CSE",
    bio: "the last layer is you",
    status: "current",
    github: "arrhamjain23",
    linkedin: "arrham-jain-568a48376",
    email: "arrhamjain@gmail.com",
  },
  {
    slug: "shreehari-b-deshpande",
    name: "Shreehari B Deshpande",
    role: "Tech Head (25-26)",
    group: "Tech",
    year: "2027, CSE",
    bio: "I am exactly what I yearn to be.",
    status: "alumni",
    linkedin: "shreehari-b-deshpande",
    email: "shreehari.deshpande2005@gmail.com",
  },
  {
    slug: "heth-mehul-shah",
    name: "Heth Mehul Shah",
    alias: "H8",
    role: "Tech Head (25-26)",
    group: "Tech",
    year: "2027, CSE",
    bio: "Put something good",
    status: "alumni",
    linkedin: "heth-shah-634848244",
    email: "hethshah12@gmail.com",
  },
  {
    slug: "rishil-abhijit-jalisatgi",
    name: "Rishil Abhijit Jalisatgi",
    role: "Tech Member",
    group: "Tech",
    year: "2027, CSE",
    bio: "For those who come after.",
    status: "alumni",
    linkedin: "rishil-jalisatgi",
    email: "rishil.aj99@gmail.com",
  },
  {
    slug: "rithvik-a-m",
    name: "Rithvik A M",
    alias: "Rithrizz",
    role: "Tech Member",
    group: "Tech",
    year: "2028, ECE",
    bio: "Many interests. One direction: forward.",
    status: "alumni",
    linkedin: "amrithvik",
    email: "rithvikam2006@gmail.com",
  },
  {
    slug: "rithvik-matta",
    name: "Rithvik Matta",
    alias: "rtk",
    role: "Founder & Club Head (25-26)",
    group: "Club",
    year: "2027, CSE",
    bio: "Heya!",
    status: "alumni",
    github: "rtk5",
    linkedin: "rithvik-matta-pes27",
    portfolio: "https://rithvikmatta.netlify.app/",
    email: "rithvik.matta@gmail.com",
  },
  {
    slug: "deepthi-venkatesh",
    name: "Deepthi Venkatesh",
    alias: "dV",
    role: "Club Member (25-26)",
    group: "Tech",
    year: "2028, CSE",
    bio: "Root access, not by accident.",
    status: "alumni",
    linkedin: "deepthi-venkatesh-1a5a80350",
    email: "dv1533709@gmail.com",
  },
  {
    slug: "rithish-barath",
    name: "Rithish Barath",
    role: "Media Head (25-26)",
    group: "Media",
    year: "2027, CSE",
    bio: "",
    status: "alumni",
    linkedin: "rithish-barath-74ba19321",
    email: "rithishbarath6@gmail.com",
  },
];

const PHOTO_SLUGS = new Set([
  "achyuth-jois-m",
  "aks-raj-singh",
  "amogh-garg",
  "ankit-bembalgi",
  "ann-gracia-s",
  "archita-agrawal",
  "arnav-deva",
  "arrham-jain",
  "blason-raj",
  "chatresh-ramasai-gudi",
  "deepthi-venkatesh",
  "hemal-s",
  "himani-nune",
  "hiranmayi-b",
  "ianna-elizabeth-reni",
  "isha-desai",
  "jyeshta-j",
  "krisha-varma-k",
  "krishnaja-jinka",
  "krithika-swaminathan",
  "manasi-trivedi",
  "manish-kumar-r",
  "nandana-shyam",
  "nikhita-medayhal",
  "p-mahema-sai",
  "prajwal-m",
  "preksha-nehru",
  "rashi-sharan",
  "riddhima-agarwal",
  "rishabh-singh",
  "rishil-abhijit-jalisatgi",
  "rithish-barath",
  "rithvik-a-m",
  "rithvik-deepak",
  "rithvik-matta",
  "saakshi-mohanty",
  "shivangi-tiwari",
  "shreehari-b-deshpande",
  "shreya-ajith",
  "shreya-surya-prakash",
  "sohan-mr",
  "sowmya-ramesh",
  "sreehaas-vangara",
  "sriya-chandu",
  "srivaibhav-n",
  "varunavi-kumbar",
]);

export function photoUrl(slug: string): string | undefined {
  return PHOTO_SLUGS.has(slug) ? `/members/${slug}.webp` : undefined;
}

export function getMember(slug: string): Member | undefined {
  return MEMBERS.find((m) => m.slug === slug);
}

/** Alumni — shown on /legacy, not /about. */
export const ALUMNI: Member[] = MEMBERS.filter((m) => m.status === "alumni").sort(
  (a, b) => a.name.localeCompare(b.name),
);

/* ------------------------------------------------------------------ */
/*  domain sub-pages (/about/[domain]) — head + vice + group roster    */
/* ------------------------------------------------------------------ */

export type Domain = {
  slug: string;
  name: string;
  group: MemberGroup;
  tagline: string;
  headSlug: string;
  viceSlug: string;
};

export const DOMAINS: Domain[] = [
  {
    slug: "tech",
    name: "Tech",
    group: "Tech",
    tagline:
      "Exploit dev, infra, tooling and the weekly CTFs. If it has a shell, Tech wants it first.",
    headSlug: "shubhika-pradeep",
    viceSlug: "amogh-garg",
  },
  {
    slug: "events",
    name: "Events",
    group: "Events",
    tagline:
      "CTFs, workshops, talks and inter-college competitions — everything with a date on it.",
    headSlug: "blason-raj",
    viceSlug: "saakshi-mohanty",
  },
  {
    slug: "media",
    name: "Media",
    group: "Media",
    tagline:
      "Writeups, socials, recaps and marketing. If it went out with the club's name on it, Media shipped it.",
    headSlug: "sohan-mr",
    viceSlug: "krithika-swaminathan",
  },
  {
    slug: "design",
    name: "Design",
    group: "Design",
    tagline:
      "Brand, posters, slides and the site. Makes the rest of it look deliberate.",
    headSlug: "shreya-ajith",
    viceSlug: "riddhima-agarwal",
  },
];

export function getDomain(slug: string): Domain | undefined {
  return DOMAINS.find((d) => d.slug === slug);
}

/** A domain's roster: current members in that group who aren't its head/vice. */
export function getDomainMembers(domainSlug: string): Member[] {
  const d = getDomain(domainSlug);
  if (!d) return [];
  const leads = new Set([d.headSlug, d.viceSlug]);
  return MEMBERS.filter(
    (m) => m.group === d.group && m.status === "current" && !leads.has(m.slug),
  ).sort((a, b) => a.name.localeCompare(b.name));
}

export function initials(name: string): string {
  return name
    .split(/\s+/)
    .map((w) => w[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();
}
